### ISSUE TITLE
Open and Empty Trash labels

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/experimental#7]
Suggest worth investigating if the "Empty Trash" and "Open" labels could be obtained from the installed locale so that they appear in the users current language rather than be hardcoded in English

i.e. python gettext

N.B. for example "Trash" is "en_US" - whereas in "en_GB" the label appears as "Rubbish bin"

**Comment by Coeur-Noir** [comment]
Here with French language set : 
![budgie_labels](https://user-images.githubusercontent.com/1895947/43870605-ab228ff4-9b78-11e8-8dc0-e57a81331320.png)
…« open » instead of « ouvrir »
Although it works nicely with disks : 
![bugie_labels_device](https://user-images.githubusercontent.com/1895947/43870717-355940b4-9b79-11e8-8f3a-21464828b693.png)
« monter et ouvrir »

**Comment by fossfreedom** [comment]
Translations are now managed by Transifex.  Issue is moot. Closing
